"""add_document_signatures_table

Revision ID: f725f1079ef0
Revises: 99d8a69d7966
Create Date: 2026-03-27 22:59:54.844850

"""

import sqlalchemy as sa

from alembic import op

revision = "f725f1079ef0"
down_revision = "99d8a69d7966"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_signatures",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("signer_id", sa.Integer(), nullable=False),
        sa.Column(
            "signed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["signer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_signatures_document_id"),
        "document_signatures",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_signatures_id"), "document_signatures", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_document_signatures_signer_id"),
        "document_signatures",
        ["signer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_signatures_signer_id"), table_name="document_signatures"
    )
    op.drop_index(op.f("ix_document_signatures_id"), table_name="document_signatures")
    op.drop_index(
        op.f("ix_document_signatures_document_id"), table_name="document_signatures"
    )
    op.drop_table("document_signatures")
    # ### end Alembic commands ###
